services:

  remote_proxy:
    container_name: remote_proxy
    image: nginx:1.27.0-alpine-slim
    restart: unless-stopped
    command: /bin/sh -c "envsubst '$$REMOTE_REGISTRY' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    ports:
      - "8000:8080"
    environment:
      REMOTE_REGISTRY: ${REMOTE_REGISTRY}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro

  registry_angular_ui:
    container_name: registry_angular_ui
    hostname: registry_angular_ui
    image: alexanderwolz/registry-angular-ui:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      REGISTRY_HOST: http://localhost:8000
      TOKEN_SECRET: myfancysupersecureappsecret
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - remote_proxy

# INFO: export REMOTE_REGISTRY in PATH variables
